### ISSUE TITLE
Add internal admin server that scatters commands across backends

### ISSUE THREAD

**Issue by masih** [ipni/indexstar#33]
It wold be nice if indexstar also mimics the admin API exposed by a regular indexer node, and upon receiving a request it sends it to all configured backends. Example usage: trigger manual sync from a specific provider. Without it, the admin sync command needs to be executed on each node individually.

Note the admin API should be exposed on a different port and be excluded from public ingress.

**Comment by gammazero** [comment]
The manual sync could also be accomplished by generating an announce message and sending it to the assigner.

**Comment by gammazero** [comment]
I think separate issues, on a case-by-case basis, are needed in place of this issue.

For example, sending admin sync is better done by sending an announcement to the assigner to forward, and so that a new indexer will get assigned if one is not already. If not using assigner, then it is unlikely that multiple indexers would be ingesting from the same provider, so scatter is probably not what is needed here.

Other admin cases, such as skipping an advertisement, unassigning a provider, freezing/unfreezing an indexer, etc., usually pertain to a single indexer. So, I think there is little need to scatter admin commands, and if there is a specific reason an issue specific to that command should be opened.

I suggest closing this issue.

**Comment by willscott** [comment]
agree that this is probably not the right issue, and we should re-open specific features we need indexstar to do
